[package]
name = "solar-blaster"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-sdk = "1.9.4"
solana-client = "1.9.4"
anchor-client = "0.20.1"
rand = "0.8.4"
shellexpand = "2.1.0"